# Generated by Django 4.0.5 on 2022-07-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Idcliente')),
                ('nombrecliente', models.CharField(max_length=50, verbose_name='nombreCliente')),
                ('destino', models.CharField(max_length=50, verbose_name='Destino')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('fono', models.IntegerField(verbose_name='Fono')),
            ],
        ),
    ]
